name: "🐞 Bug Report"
description: "Report a bug with as much detail as you can. Please attach screenshots or logs if available."
title: "[Bug] "
labels: ["bug"]
assignees: []
body:
  - type: dropdown
    id: app
    attributes:
      label: "Which app?"
      description: "Choose the app where the bug appears"
      options:
        - "Nextlivin Manage"
        - "Nextlivin Tenant"
  - type: dropdown
    id: feature
    attributes:
      label: "Feature"
      description: "Which feature affected?"
      options:
        - "Home"
        - "Dashboard"
        - "User"
        - "Unit"
        - "Worktrack"
        - "Feedback"   
        - "Billing"
        - "Package"
        - "Visitor"
        - "Inventory"
        - "Notifications"
        - "Profile"
        - "Team Chat"
        - "Chat Bot"
        - "My Work"
        - "General"      
  - type: input
    id: version
    attributes:
      label: "App version"
      description: "Example: 1.0.3"
      placeholder: "e.g. 1.0.3"
  - type: dropdown
    id: platform
    attributes:
      label: "Platform"
      options:
        - "Android"
        - "iOS"
        - "Web"        
  - type: input
    id: device
    attributes:
      label: "OS"
      description: "OS version (optional)"
      placeholder: "e.g. Android 13"
  - type: textarea
    id: steps
    attributes:
      label: "Bug Description"
      description: "You can describe how to reproduce the bug"
      placeholder: |
        1. Go to ...
        2. Tap ...
        3. Observe ...
  - type: textarea
    id: expected
    attributes:
      label: "Expected result"
      description: "What did you expect to happen?"
  - type: textarea
    id: attachments
    attributes:
      label: "Attachments (screenshots / videos)"
      description: |
        Upload images/videos with full screen.
  - type: input
    id: reporter_email
    attributes:
      label: "Reporter email"
      description: "Enter your email"
