name: "🐞 Bug Report"
description: "Report a bug with as much detail as you can. Please attach screenshots or logs if available."
title: "[Bug] Report Bug Form"
labels: ["bug"]
assignees: []
body:
  - type: input
    id: email
    attributes:
      label: Email Address
    validations:
      required: true
  - type: dropdown
    id: app
    attributes:
      label: "Which app?"
      options:
        - "Nextlivin Manage"
        - "Nextlivin Tenant"
      validations:
      required: true
  - type: dropdown
    id: feature
    attributes:
      label: "Feature"
      options:
        - "Home"
        - "Dashboard"
        - "User"
        - "Unit"
        - "Worktrack"
        - "Feedback"   
        - "Billing"
        - "Package"
        - "Visitor"
        - "Inventory"
        - "Notifications"
        - "Profile"
        - "Team Chat"
        - "Chat Bot"
        - "My Work"
        - "General"  
      validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "App version"
      placeholder: "e.g. 1.0.3"
      validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: "Platform"
      options:
        - "Android"
        - "iOS"
        - "Web" 
      validations:
      required: true
  - type: input
    id: device
    attributes:
      label: "OS"
      placeholder: "e.g. Android 13"
      validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Bug Description"
      placeholder: |
        1. Go to ...
        2. Tap ...
        3. Observe ...
  - type: textarea
    id: expected
    attributes:
      label: "Expected result"
  - type: textarea
    id: attachments
    attributes:
      label: "Attachments (screenshots / videos)"
      description: |
        Upload images/videos with app full screen.
